# Generated by Django 3.1.7 on 2021-02-22 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=500)),
                ('ContentSubtitle1', models.CharField(max_length=100)),
                ('Content1', models.TextField(blank=True, max_length=500, null=True)),
                ('ContentSubtitle2', models.CharField(blank=True, max_length=100, null=True)),
                ('Content2', models.TextField(blank=True, max_length=500, null=True)),
                ('ContentSubtitle3', models.CharField(blank=True, max_length=100, null=True)),
                ('Content3', models.TextField(blank=True, max_length=500, null=True)),
                ('ContentSubtitle4', models.CharField(blank=True, max_length=100, null=True)),
                ('Content4', models.TextField(blank=True, max_length=500, null=True)),
                ('ContentSubtitle5', models.CharField(blank=True, max_length=100, null=True)),
                ('Content5', models.TextField(blank=True, max_length=500, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('機械学習', 'Machine Learning'), ('ディープラーニング', 'Deep Learning'), ('データ分析', 'Data Analysis'), ('Python 基礎', 'Python Basic'), ('Django', 'Django'), ('環境構築', 'environ_set'), ('その他', 'etc')], max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
